zuul:
  # 全部服务忽略敏感头(全部服务都可传递Cookie)
  sensitive-headers: 
  routes:
  # /myProduct/product/list -> /product/prodcut/list
    myProduct:
      path: /myProduct/**
      serviceId: product
  # 排除某些路由
  ignored-patterns:
    - /**/product/listForOrder
spring:
  redis:
    host: 192.168.99.101
    port: 6379
