spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    data-username: root
    data-password: bjtungirc
    url: jdbc:mysql://192.168.200.140:3306/SpringCloud_SellerBuyer?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.99.101
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.99.101
    port: 6379
  jpa:
    show-sql: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic  
env: dev9
