spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    data-username: root
    data-password: bjtungirc
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_SellerBuyer?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.99.101
    port: 6379
  jpa:
    show-sql: true
